CREATE DATABASE CSDLDD17
CREATE TABLE HH
(MAHH VARCHAR(10) PRIMARY KEY,
TENHH VARCHAR(30),
SOLGTON INT,
CHLOAI VARCHAR(20),)
CREATE TABLE NCC
(MANCC VARCHAR(20) PRIMARY KEY,
TENNCC VARCHAR(20),
DC VARCHAR(12),)
CREATE TABLE CCHH
(MNCC VARCHAR(10) PRIMARY KEY,
MAHH VARCHAR(10) FOREIGN KEY REFERENCES HH(MAHH),
slg INT,);
select	*
from
wher
backup database CSDLDD17 to disk ='E:\quanly.bak'